# dockerfile to build pcmdpy on GPU

# start with base of nvidia's CUDA toolkit (Ubuntu based)
FROM nvidia/cuda:9.0-devel

SHELL ["/bin/bash"]

ENV LD_LIBRARY_PATH="/usr/local/cuda/lib64/:${LD_LIBRARY_PATH}"

# load python and dependencies
COPY install/*.sh install/
RUN install/base.sh
RUN install/python_base.sh

ENV HOME=/root
ENV PATH=${HOME}/miniconda/bin:${HOME}/.local/bin/:${PATH}
ENV PYTHONPATH=${HOME}/miniconda/lib/python3.6/site-packages
